cloudscape-design/documenter

- fixtures/components/deprecated-tag/example/index.tsx
- src/components/build-definition.ts
- test/components/deprecated-tag.test.ts
Deprecated tag is not shown in Events definition in component API tab. For example, `onButtonClick` of Alert is deprecated but is not shown on website https://cloudscape.design/components/alert/?tabId=api. The PR is to add deprecatedTag to events. 
Tested locally on website
> fix: Add deprecatedTag to events

- .github/workflows/build-lint-test.yml
- .github/workflows/dry-run.yml
- .github/workflows/release.yml
This PR switches to the new shared repository for GitHub workflows and actions: https://github.com/cloudscape-design/actions.
For the most recent changes to the shared workflows, see https://github.com/cloudscape-design/actions/pull/1. The new configuration was successfully tested in this Draft PR: https://github.com/cloudscape-design/components/pull/1672.
> chore: Switch to new actions repo for workflows

- src/components/components-extractor.ts
- src/schema/utils.ts
Modified the `returnsReactContent` function to check for `'JSX.Element'` and `'React.ReactPortal'` in `type.symbolFullyQualifiedName` using string `endsWith`. 
This change works with different TypeScript module resolution strategies where the fully qualified name might resolve to a module-specific path, e.g., `'"node_modules/@types/react/ts5.0/jsx-runtime".JSX.Element'`, instead of only matching exact paths like `'global.JSX.Element'` or `'React.ReactPortal'`.
> chore: Update returnsReactContent to handle varied JSX.Element or ReactPortal paths

- package-lock.json
- package.json
Allow this package to run `npm install` without the `--force` flag. 
> chore: Use explicit typescript override

- fixtures/components/analytics-tag/example/index.tsx
- fixtures/components/analytics-tag/tsconfig.json
- src/components/build-definition.ts
- src/components/interfaces.ts
- test/components/analytics-tag.test.ts
As part of adding in the analyticsMetadata property in the components, we will be tagging the property document with an `analytics` tag to allow for better documentation on the website.
> chore: Add support for analytics tag

- .github/workflows/build-lint-test.yml
- .github/workflows/dry-run.yml
to enable merge queue feature in the repo, trigger workflows that are checked in PR when merge queue is requested.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
tested in global-styles repo: https://github.com/cloudscape-design/global-styles/pull/48
> chore: Trigger required workflows on merge_group event

- fixtures/components/third-party-import-types/button/index.tsx
- fixtures/components/third-party-import-types/button/interfaces.ts
- fixtures/components/third-party-import-types/node_modules_mock/icon/index.d.ts
- fixtures/components/third-party-import-types/node_modules_mock/icon/interfaces.d.ts
- fixtures/components/third-party-import-types/tsconfig.json
- src/bootstrap/index.ts
- src/components/components-extractor.ts
- src/components/index.ts
- test/components/test-helpers.ts
- test/components/third-party-import-types.test.ts
*Description of changes:* This PR adds nodeModulesInputFilePaths to accept additional file paths to be added to inputFiles option of typedoc. When it is defined, it enables includeDeclarations and excludeExternals as well. More details can be found in Uzu5AkM2GZiY. Related chat components PR: https://github.com/cloudscape-design/chat-components/pull/18
> chore: Support third party type imports

- fixtures/components/system-tag/button/index.tsx
- fixtures/components/system-tag/button/interfaces.ts
- fixtures/components/system-tag/tree/index.tsx
- fixtures/components/system-tag/tsconfig.json
- src/components/component-definition.ts
- src/components/extractor.ts
- src/components/index.ts
- src/components/interfaces.ts
- src/components/object-definition.ts
- src/components/type-utils.ts
- test/components/default-values-extractor.test.ts
- test/components/simple.test.ts
- test/components/system-tag.test.ts
- test/components/test-helpers.ts
- test/components/value-descriptions-extractor.test.ts
Implement design described in this quip: GPxrABVyujLV
> feat: Support `awsuiSystem` jsdoc tags

- src/components/index.ts
- test/components/legacy.test.ts
- test/components/test-helpers.ts
It is now 4 arguments, with holes in between, `documentComponents(tsconfig, glob, undefined, options)`. Time to switch from multi-arguments to a single `options` argument
> chore: fix documentComponents functions signature

- src/components/component-definition.ts
- src/components/index.ts
- src/components/interfaces.ts
- test/components/complex-types.test.ts
[Sometimes](https://github.com/cloudscape-design/components/blob/6b44f715bda9d47f27afc95d1733e4e83bba1419/build-tools/tasks/docs.js#L36) we need dash-cased, sometimes camelCased name. Instead of always converting one to another, we can just export both from a single place
> feat: Export dash-cased names

- src/components/type-utils.ts
- test/components/value-descriptions-extractor.test.ts
Fixing a bug where an irrelevant comment may cause an unexpected systemTag value to be produced
> fix: Skip non-system comments when extracting descriptions

- package.json
- src/components/index.ts
- src/index.ts
- test/components/errors.test.ts
- test/components/test-helpers.ts
- test/components/writer.test.ts
- tsconfig.json
- vite.config.ts
Add `writeComponentsDocumentation` function which not only generate documentation objects, but actually writes them to disk. Also see the respective components change: https://github.com/cloudscape-design/components/pull/3448
This will reduce duplications like this
* https://github.com/cloudscape-design/components/blob/053e0325143b228c206c7bb3d82c7b4b0e7d0909/build-tools/tasks/docs.js#L34-L44
* https://github.com/cloudscape-design/chat-components/blob/main/scripts/docs.js#L28-L38
* https://github.com/cloudscape-design/board-components/blob/69b272ab1137af6c53d4a7adc325066a428fa952/scripts/docs.js#L28-L38
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> feat: Add helper to write documentation files

- src/components/index.ts
- test/components/writer.test.ts
Fixing cause of this revert: https://github.com/cloudscape-design/components/pull/3467
The build error was:
```
error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
```
Fixed the error and added a test to validate it here in this package build
> fix: generated type declarations for output files

- src/components/index.ts
Follow up for this: https://github.com/cloudscape-design/documenter/pull/70
The type declaration still does not work when using `"moduleResolution": "node16"` typescript config
> update export declaration

- codecov.yaml
- fixtures/test-utils/glob-test/a.ts
- fixtures/test-utils/glob-test/b.ts
- fixtures/test-utils/glob-test/tsconfig.json
- package.json
- src/index.ts
- src/test-utils-new/extractor.ts
- src/test-utils-new/index.ts
- src/test-utils-new/interfaces.ts
- test/test-utils/__snapshots__/doc-generation.test.ts.snap
- test/test-utils/doc-generation.test.ts
- test/test-utils/test-helpers.ts
- test/test-utils/usage.test.ts
- test/test-utils/writer.test.ts
> chore: Rewrite test utils doc generator

- package-lock.json
Ran `npm audit fix` and committed the result
> chore: Fix npm audit

- src/index.ts
The documentComponents util is to be used for snapshot tests on internal APIs that are not meant to be exposed in the api-docs, see: https://github.com/cloudscape-design/chart-components/pull/70.
> chore: Exposes documentComponents util

- fixtures/test-utils/advanced-types/index.ts
- fixtures/test-utils/exports/cards.ts
- fixtures/test-utils/exports/index.ts
- src/components/type-utils.ts
- src/test-utils-new/extractor.ts
- src/test-utils-new/index.ts
- src/test-utils-new/interfaces.ts
- test/test-utils/__snapshots__/doc-generation.test.ts.snap
- test/test-utils/doc-generation.test.ts
- test/test-utils/test-helpers.ts
Compatibility with the old test-utils-doc generator
1. Support `typeArguments` field
2. Add new `isNullable` field to avoid manual parsing `type.name.split(' | ')` on the website end
*Testing*
Expected to fail snapshot tests downstream, already prepared an update: https://github.com/cloudscape-design/test-utils/pull/98
> feat: extract generic types and nullable information as separate fields

- fixtures/test-utils/exports/core.ts
- fixtures/test-utils/exports/index.ts
- fixtures/test-utils/exports/radio-group.ts
- src/test-utils-new/extractor.ts
- test/test-utils/__snapshots__/doc-generation.test.ts.snap
- test/test-utils/doc-generation.test.ts
Fixing a bug where `RadioButtonWrapper` is not included into the final documentation output, because it is only used as a part of `MultiElementWrapper<RadioButtonWrapper>` generic type
> fix: MultiElementWrapper support

- src/components/component-definition.ts
- src/components/extract-value-descriptions.ts
- src/components/extractor.ts
- src/components/index.ts
- src/components/object-definition.ts
- src/shared/type-utils.ts
- src/test-utils/extractor.ts
- src/test-utils/interfaces.ts
- test/components/value-descriptions-extractor.test.ts
- test/shared/type-utils.test.ts
1. Extract type-utils to `shared` directory because they used in both test-utils and components
2. Update test-utils type remove some not needed optional flags
> chore: Update files structure
